### ISSUE TITLE
GoLang SDK availability

### ISSUE THREAD

**Issue by nvibert** [vmware-archive/terraform-provider-vmc#14]
FYI, when I follow the instructions to download the provider, I get a fatal error and a crash when running 'go get'. 

go: github.com/vmware/vsphere-automation-sdk-go
"fatal: repository 'https://github.com/vmware/vsphere-automation-sdk-go/' not found"

I assume it's because the GoLang SDKs have not been pushed on GitHub yet ?

**Comment by shylasrinivas** [comment]
Thanks for reporting this issue. Yes, the GoLang SDK is not public on GitHub due to which this error comes up. We are working on it and will follow up on this issue as soon the SDK is released.

**Comment by strefethen** [comment]
@nvibert Apologies. When we have a better understanding of the Go SDK timeline we'll follow up. In the meantime we've updated the README so other can avoid running into this problem.

**Comment by nvibert** [comment]
Thanks @shylasrinivas and @strefethen for the quick replies. I'll wait patiently ;-)
