### ISSUE TITLE
HashiCorp Partner Provider Program Review

### ISSUE THREAD

**Issue by cgriggs01** [vmware-archive/terraform-provider-vmc#16]
Hey Team,

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  The review was done on the develop branch at git commit   [ccb9c2c](https://github.com/vmware/terraform-provider-vmc/commit/ccb9c2c1cf9720f4125c40c0393b67c631d6cf4c) 

- [x] In the main docs index page, you are listing out all the arguments for all the reousrces, but you should be only listing the arguments that are taken in by provider.g.  —> refresh_token, vmc_url, csp_url

- [x] Attributes should be read and set on Read so that differences between the configuration and the actual state can be caught. Any non-scalar values (TypeList, TypeSet, TypeMap) should have errors checked when setting. The reasoning for this is that the provider should never `panic` and should error out with an error statement instead. 

- [x] The Go SDK that you’ve build for this provider at GitHub.com/vmware/vsphere-automation-sdk-go is currently a private repository but must be made publicly available in order to build and certify this provider. 

- [x] The go file name [HttpClient.go](https://github.com/vmware/terraform-provider-vmc/blob/master/vmc/HttpClient.go) is using CamelCase, but should be all lowercase. 

- [x] You are already using Go Modules to manage the providers dependancies which is great, but in addition to that, we ask that you checkin all the required dependancies into a `vendor/` directory. This is so that our nightly testing environment does ping GitHub for ever dependancies in all 100+ TF providers. 

- [x] The MPL2.0 License is correct, but could you update it to follow the standard licensing format and naming for all TF providers —> [MPL2.0 LICENSE](https://github.com/terraform-providers/terraform-provider-github/blob/master/LICENSE)

- [x] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. 

- [x] All of the Terraform provider follow the same README.md formatting, see this one —> [terraform-provider-github/README.md](https://github.com/terraform-providers/terraform-provider-github/blob/master/README.md)

- [x] The main.tf file and any other provider usage examples should reside under a `examples/` directory in the root of the provider repo. 

- [x] All providers in the terraform-providers/ GitHub org have a TravisCI check run on each PR that is opened. Can you please add a .travis.yaml file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)

- [x] One of our Terraform Ecosystem engineers built a linter to help align coding best practices for providers. You should use it along with your development. https://github.com/bflad/tfproviderlint

- [x] There are a few files that should be removed from the repository as they are not used in the official testing and releasing the provider. Please remove;  CODE-OF-CONDUCT.md, CONTRIBUTING.md, NOTICE.txt, docscheck.sh, errcheck.sh, websitefmtcheck.sh

**Comment by saloneerege** [comment]
Thanks @cgriggs01 for reviewing the provider and providing your feedback. We will make these changes and notify you as soon as they are all completed.

**Comment by saloneerege** [comment]
@cgriggs01  for the files CODE-OF-CONDUCT.md, CONTRIBUTING.md, NOTICE.txt, they have been added as a part of the open source process for the provider on VMware Github site.

**Comment by cgriggs01** [comment]
Hi @saloneerege, 

That should be ok, these are not typical throughout the rest of the providers, but if you need to keep these files, it will not block the certification and release. 

Thanks for the question.

**Comment by saloneerege** [comment]
Hi @cgriggs01 ,
  Thanks for the clarification.

**Comment by sumitAgrawal007** [comment]
Hi @cgriggs01 ,
In the second point "Attributes should be read and set on Read so that differences between the configuration and the actual state can be caught"
This is not very clear, Can you give me an example to clarify further?

**Comment by cgriggs01** [comment]
Hey @sumitAgrawal007,

The main point in that issue is that, when the provider uses a non scaler value (map, set, or list), the set should be error checked so that it will not panic or hit a segmentation fault. 

I hope this helps, let me know if you have any further questions.

Best,
Chris

**Comment by cgriggs01** [comment]
Hi @sumitAgrawal007 

Thanks for address all feedback. Everything looks great, the last item before we can release this provider it to get the acceptance tests passing. I was able to create an API Token from the account you provided, but hit the same error on each of the test. Could you help me to resolve this. Here is my 
[test_output.txt](https://github.com/vmware/terraform-provider-vmc/files/4190575/test_output.txt)

Let me know if you have any suggestions. 

Thanks,
Chris

**Comment by sumitAgrawal007** [comment]
Hi @cgriggs01 ,
Looks like the refresh token you are using doesn't have access, so you are getting unauthorised error. Are you able to create any resource using the same refresh_token?

**Comment by cgriggs01** [comment]
@sumitAgrawal007,

I have not been able to create any resource. The refresh_token was generated [here](https://console.cloud.vmware.com/csp/gateway/portal/#/user/tokens).

Thanks for you help on this.

**Comment by shylasrinivas** [comment]
@cgriggs01 
It looks like your account does not have the right permissions. Does your account belong to "Hashicorp EA Verification" org?  We are following up with the org owner @kusantosh .

**Comment by shylasrinivas** [comment]
@cgriggs01 We have received confirmation that the account you are using has admin privileges. From the test_output.txt file, I can see that you are using short org ID. Can you change that to long org ID? If you click on the short Organization ID in VMC console, long ID is revealed. Please use that in the ORG_ID env variable before running make testacc.

**Comment by cgriggs01** [comment]
Thanks for that but I am getting the same error but with the long organization ID.

**Comment by cgriggs01** [comment]
The organization I have access to is called "Terraform Organization"

**Comment by shylasrinivas** [comment]
Zoom? I can send you an invite.

**Comment by cgriggs01** [comment]
yes, you can send it to cgriggs@hashicorp.com

**Comment by shylasrinivas** [comment]
I circled back with Santosh. According to him - "Terraform Organization" is an old org and should not be used. You can continue to use "Hashicorp EA Verification" org.

**Comment by cgriggs01** [comment]
Thanks @shylasrinivas,

That feedback we discuss was changing the hard coded value "DX AUTO Core Team" to an environment variable that can be set for running the test [data_source_vmc_org_test](https://github.com/vmware/terraform-provider-vmc/blob/master/vmc/data_source_vmc_org_test.go#L21) and would it be possible to change the env variable REFRESH_TOKEN to something more aligned with api_token which is how it is documented. 

Thanks for your help today!

**Comment by shylasrinivas** [comment]
@cgriggs01 Based on your feedback, we have made changes to the acceptance tests. Please review.

**Comment by saloneerege** [comment]
@cgriggs01 Please can provide any further feedback. Appreciate your help.

**Comment by saloneerege** [comment]
@cgriggs01 can I close this issue since all the points mentioned in the above feedback comments have been addressed already ?

**Comment by cgriggs01** [comment]
Hey @saloneerege, 

Let us keep this open as a thread to finish up the provider review. 

Thanks for making the changes that where asked. I just have some feedback regarding the environment variables required for testing. 

- [x] All the environment variables declared in the provider should all be capitalized. The variable [APIToken](https://github.com/vmware/terraform-provider-vmc/blob/master/vmc/provider_test.go#L37) should be listed as `API_TOKEN` or even `VMC_API_TOKEN`. Can you make sure this happens for all the providers environment variables. 

- [ ] For running the acceptance tests, what is the AWSAccountNumber that I should be using when running the tests?

We are very close to the end. Thanks for all you work on this.

**Comment by shylasrinivas** [comment]
@cgriggs01 - for the first point - env variables are uppercase and have been moved to constants.go
https://github.com/vmware/terraform-provider-vmc/blob/master/vmc/constants.go#L17
When users run acceptance tests - the uppercase keys are displayed in the error.

**Comment by cgriggs01** [comment]
@shylasrinivas,

Thanks for that clarification, marking that complete now.

**Comment by saloneerege** [comment]
Hi @cgriggs01,
     Thanks for reaching out.  I have sent you an email with steps describing how to get the AWS account number. I can even setup a call on Zoom if you prefer that.

Thanks,
Salonee

**Comment by cgriggs01** [comment]
Thanks for clarifying. Got it straighten out now. 

Everything checks out so far. I'd like to start the migration and release process tomorrow. How does that sound to ya'll?

- A repository under the same name `terraform-providers-vmc` will be created in the  [github.com/terraform-repositories/](http://github.com/terraform-repositories/)  organization. 
- Your provider code will be pushed up to the new repository
- The binaries during release are pulled from the master branch. 
- A `stable-website` branch will be created, this is where the  [terraform.io](http://terraform.io/)  provider documentation is source from. During each release, a bot will commit the changes in your master branch to the stable-website branch. If you need to make changes to the provider website docs in between releases, you can cherry-pick the commits to the stable-website branch. 
- The first release will be tagged `1.0.0` per the CHANGELOG.md
- You and whomever else on your team will be granted “write” access over the new repository, you are still seen as the owners and maintainers of the provider, before I grant you access, you’ll must review and agree to our community guidelines, which I’ll include below. 
- Whomever is added as a maintainer to the provider repository will also be granted an account on our #committers-terraform Slack channel, where you will request new versioned releases of the provider. 

~ Community Guideline and Etiquette ~
We value our community contributors and their time and generally tend to avoid setting any particular obligations, however before you do participate in the community as a maintainer we kindly ask you to read the maintainer etiquette document: https://github.com/hashicorp/terraform/blob/master/docs/maintainer-etiquette.md. It briefly describes the process each collaborator follows when reviewing & merging PRs.

Communicating on GitHub can sometimes be challenging. We expect our community to follow the guidelines at https://www.hashicorp.com/community-guidelines/, and for maintainers to lead as examples in that context. Please take time to review those guidelines, unless you have done so already.

Lastly, we want our contributors and their accounts to be safe, especially when accessing GitHub. Please make sure you have 2FA enabled for your account. If not, here's how to proceed: https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/

Let me know once you reviewed both documents, whether you agree to follow them, and that you have 2FA enabled for your GitHub account.

If you'd like to discuss or clarify any of the above before agreeing, please let me know; otherwise, I'll continue the maintainer onboarding process by getting you set up with Github, Slack, and CI access.

**Comment by saloneerege** [comment]
Hi @cgriggs01 ,
    Thanks for reviewing our changes and thanks for sharing next steps about releasing the provider. We will review the documents you have share and enable 2FA in our Github account. We will notify you as soon as we have completed the needful.

**Comment by saloneerege** [comment]
Hi @cgriggs01 ,
       We have reviewed the documents and have enabled 2FA authentication. Please let us know if there is anything else needed on our end for the release process.

Thanks,
Salonee

**Comment by saloneerege** [comment]
Closing this issue since the terraform provider has been released.
