### ISSUE TITLE
vsphere-automation-sdk-go is not public. 

### ISSUE THREAD

**Issue by rshade** [vmware-archive/terraform-provider-vmc#19]
I tried building this plugin but I can't get to  https://github.com/vmware/vsphere-automation-sdk-go.

**Comment by saloneerege** [comment]
@rshade Apologies. Thanks for reporting this issue. The vsphere-automation-sdk-go is currently private on Github and is in the process of becoming public. When we have a better understanding of the Go SDK timeline we'll follow up.

**Comment by rshade** [comment]
@saloneerege thank you.

**Comment by strefethen** [comment]
@rshade FYI, the Go SDK is now publicly available.

Regards

**Comment by rshade** [comment]
@strefethen thank you. `go get` now works.
